name: github CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: cd ./src && make build
    - name: test
      run: cd ./src && make test
    - name: pre-package
      run: sudo apt install -y debhelper-compat build-essential
    - name: package
      run: dpkg-buildpackage -us -uc
    - name: working-test
      run: cd .. && ls -la

    - name: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: Bombaclat
        release_name: Release Bomboclat
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ../laba1spo_1.0.0_amd64.deb # Путь к файлам для релиза
        asset_name: laba1spo_1.0.0_amd64.bin
        asset_content_type: application/octet-stream
