name: github CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: cd ./src && make build
    - name: test
      run: cd ./src && make test
    - name: pre-package
      run: sudo apt install -y debhelper-compat build-essential
    - name: package
      run: dpkg-buildpackage -us -uc
    - name: working-test
      run: cd .. && ls -la

    - name: create-release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifactErrorsFailBuild: true 
        artifact: ../laba1spo_1.0.0_amd64.deb  
        body: Bomboclat 
        name: zxcBomboclat52 
        tag: laba1spo-release
        token: ${{ secrets.MY_SECRET_NAME }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: deb-package
          path: .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

      - name: Verify container
        run: |
          docker run --rm ${{ env.DOCKER_IMAGE }}:latest
